### getAllMessges
GET http://localhost:3000/messages

### createMessage
POST http://localhost:3000/messages
Content-Type: application/json

{
    "message":"hi collins",
    "messageUrl": "www.img.com"
}

### getMessage
GET http://localhost:3000/messages/83